name: emergency_room_service_server
description: A new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bcrypt: ^1.1.3
  dart_frog: ^1.1.0
  dart_jsonwebtoken: ^2.14.2
  dotenv: ^4.2.0
  postgres: ^3.4.8

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.25.5
  very_good_analysis: ^7.0.0

dependency_overrides:
  vm_service: ^15.0.0